In [2]:
import pandas as pd
import numpy as np

nr_bazy = len('Krysztowiak')%5+1
nr_bazy

2

chunksize, decimal

In [3]:
df = pd.read_csv('tb.csv')
df

,iso2,year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
0,AD,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AD,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AD,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD,1993,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5764,ZW,2004,14581.0,NaN,NaN,187.0,833.0,2908.0,2298.0,1056.0,...,NaN,NaN,225.0,1140.0,2858.0,1565.0,622.0,214.0,111.0,NaN
5765,ZW,2005,13155.0,NaN,NaN,210.0,837.0,2264.0,1855.0,762.0,...,NaN,NaN,269.0,1136.0,2242.0,1255.0,578.0,193.0,603.0,NaN
5766,ZW,2006,12718.0,NaN,NaN,215.0,736.0,2391.0,1939.0,896.0,...,NaN,NaN,237.0,1020.0,2424.0,1355.0,632.0,230.0,96.0,NaN
5767,ZW,2007,10583.0,6.0,132.0,138.0,500.0,3693.0,0.0,716.0,...,7.0,178.0,185.0,739.0,3311.0,0.0,553.0,213.0,90.0,NaN
5768,ZW,2008,9830.0,NaN,NaN,127.0,614.0,0.0,3316.0,704.0,...,NaN,NaN,145.0,840.0,0.0,2890.0,467.0,174.0,105.0,0.0

In [42]:
df_np = df[40:50].to_numpy()
df_np

array([['AE', 2004, 57.0, nan, nan, 1.0, 7.0, 6.0, 7.0, 3.0, 1.0, 7.0,
        nan, nan, nan, 3.0, 6.0, 2.0, 7.0, 2.0, 2.0, 3.0, nan],
       ['AE', 2005, 62.0, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       ['AE', 2006, 52.0, 0.0, 0.0, 0.0, 5.0, 3.0, 7.0, 3.0, 1.0, 4.0,
        nan, 0.0, 2.0, 2.0, 6.0, 4.0, 5.0, 3.0, 4.0, 5.0, nan],
       ['AE', 2007, 56.0, 0.0, 2.0, 2.0, 5.0, 6.0, 3.0, 4.0, 3.0, 10.0,
        nan, 0.0, 1.0, 1.0, 8.0, 6.0, 3.0, 2.0, 0.0, 0.0, nan],
       ['AE', 2008, 50.0, 0.0, 0.0, 0.0, 6.0, 1.0, 7.0, 5.0, 3.0, 6.0,
        0.0, 0.0, 0.0, 0.0, 10.0, 4.0, 1.0, 1.0, 3.0, 3.0, 0.0],
       ['AF', 1980, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       ['AF', 1981, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       ['AF', 1982, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       ['AF', 1983, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       ['AF', 1984, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
      dtype=object)

In [58]:
data = [[None, None, None, None, None]]
data

[[None, None, None, None, None]]

In [59]:
for row in df_np:
    if(row[5] > 0):
        data.append([row[0], row[1], 'M', "<14", row[5]])
    if(row[6] > 0):
        data.append([row[0], row[1], 'M', "15-24", row[6]])
    if(row[7] > 0):
        data.append([row[0], row[1], 'M', "25-34", row[7]])
    if(row[8] > 0):
        data.append([row[0], row[1], 'M', "35-44", row[8]])
    if(row[9] > 0):
        data.append([row[0], row[1], 'M', "45-54", row[9]])
    if(row[10] > 0):
        data.append([row[0], row[1], 'M', "55-64", row[10]])
    if(row[11] > 0):
        data.append([row[0], row[1], 'M', ">65", row[11]])
    if(row[12] > 0):
        data.append([row[0], row[1], 'M', "nan", row[12]])

    if(row[15] > 0):
        data.append([row[0], row[1], 'F', "<14", row[15]])
    if(row[16] > 0):
        data.append([row[0], row[1], 'F', "15-24", row[16]])
    if(row[17] > 0):
        data.append([row[0], row[1], 'F', "25-34", row[17]])
    if(row[18] > 0):
        data.append([row[0], row[1], 'F', "35-44", row[18]])
    if(row[19] > 0):
        data.append([row[0], row[1], 'F', "45-54", row[19]])
    if(row[20] > 0):
        data.append([row[0], row[1], 'F', "55-64", row[20]])
    if(row[21] > 0):
        data.append([row[0], row[1], 'F', ">65", row[21]])
    if(row[22] > 0):
        data.append([row[0], row[1], 'F', "nan", row[22]])
data = data[1:]
print(data)

[['AE', 2004, 'M', '<14', 1.0], ['AE', 2004, 'M', '15-24', 7.0], ['AE', 2004, 'M', '25-34', 6.0], ['AE', 2004, 'M', '35-44', 7.0], ['AE', 2004, 'M', '45-54', 3.0], ['AE', 2004, 'M', '55-64', 1.0], ['AE', 2004, 'M', '>65', 7.0], ['AE', 2004, 'F', '<14', 3.0], ['AE', 2004, 'F', '15-24', 6.0], ['AE', 2004, 'F', '25-34', 2.0], ['AE', 2004, 'F', '35-44', 7.0], ['AE', 2004, 'F', '45-54', 2.0], ['AE', 2004, 'F', '55-64', 2.0], ['AE', 2004, 'F', '>65', 3.0], ['AE', 2006, 'M', '15-24', 5.0], ['AE', 2006, 'M', '25-34', 3.0], ['AE', 2006, 'M', '35-44', 7.0], ['AE', 2006, 'M', '45-54', 3.0], ['AE', 2006, 'M', '55-64', 1.0], ['AE', 2006, 'M', '>65', 4.0], ['AE', 2006, 'F', '<14', 2.0], ['AE', 2006, 'F', '15-24', 6.0], ['AE', 2006, 'F', '25-34', 4.0], ['AE', 2006, 'F', '35-44', 5.0], ['AE', 2006, 'F', '45-54', 3.0], ['AE', 2006, 'F', '55-64', 4.0], ['AE', 2006, 'F', '>65', 5.0], ['AE', 2007, 'M', '<14', 2.0], ['AE', 2007, 'M', '15-24', 5.0], ['AE', 2007, 'M', '25-34', 6.0], ['AE', 2007, 'M', '35-44', 3.0], ['AE', 2007, 'M', '45-54', 4.0], ['AE', 2007, 'M', '55-64', 3.0], ['AE', 2007, 'M', '>65', 10.0], ['AE', 2007, 'F', '<14', 1.0], ['AE', 2007, 'F', '15-24', 8.0], ['AE', 2007, 'F', '25-34', 6.0], ['AE', 2007, 'F', '35-44', 3.0], ['AE', 2007, 'F', '45-54', 2.0], ['AE', 2008, 'M', '15-24', 6.0], ['AE', 2008, 'M', '25-34', 1.0], ['AE', 2008, 'M', '35-44', 7.0], ['AE', 2008, 'M', '45-54', 5.0], ['AE', 2008, 'M', '55-64', 3.0], ['AE', 2008, 'M', '>65', 6.0], ['AE', 2008, 'F', '15-24', 10.0], ['AE', 2008, 'F', '25-34', 4.0], ['AE', 2008, 'F', '35-44', 1.0], ['AE', 2008, 'F', '45-54', 1.0], ['AE', 2008, 'F', '55-64', 3.0], ['AE', 2008, 'F', '>65', 3.0]]

In [60]:
result_df = pd.DataFrame(data, columns=['iso2', 'year', 'sex', 'age', 'count'])
result_df

   iso2  year sex    age  count
0    AE  2004   M    <14    1.0
1    AE  2004   M  15-24    7.0
2    AE  2004   M  25-34    6.0
3    AE  2004   M  35-44    7.0
4    AE  2004   M  45-54    3.0
5    AE  2004   M  55-64    1.0
6    AE  2004   M    >65    7.0
7    AE  2004   F    <14    3.0
8    AE  2004   F  15-24    6.0
9    AE  2004   F  25-34    2.0
10   AE  2004   F  35-44    7.0
11   AE  2004   F  45-54    2.0
12   AE  2004   F  55-64    2.0
13   AE  2004   F    >65    3.0
14   AE  2006   M  15-24    5.0
15   AE  2006   M  25-34    3.0
16   AE  2006   M  35-44    7.0
17   AE  2006   M  45-54    3.0
18   AE  2006   M  55-64    1.0
19   AE  2006   M    >65    4.0
20   AE  2006   F    <14    2.0
21   AE  2006   F  15-24    6.0
22   AE  2006   F  25-34    4.0
23   AE  2006   F  35-44    5.0
24   AE  2006   F  45-54    3.0
25   AE  2006   F  55-64    4.0
26   AE  2006   F    >65    5.0
27   AE  2007   M    <14    2.0
28   AE  2007   M  15-24    5.0
29   AE  2007   M  25-34    6.0
30   AE  2007   M  35-44    3.0
31   AE  2007   M  45-54    4.0
32   AE  2007   M  55-64    3.0
33   AE  2007   M    >65   10.0
34   AE  2007   F    <14    1.0
35   AE  2007   F  15-24    8.0
36   AE  2007   F  25-34    6.0
37   AE  2007   F  35-44    3.0
38   AE  2007   F  45-54    2.0
39   AE  2008   M  15-24    6.0
40   AE  2008   M  25-34    1.0
41   AE  2008   M  35-44    7.0
42   AE  2008   M  45-54    5.0
43   AE  2008   M  55-64    3.0
44   AE  2008   M    >65    6.0
45   AE  2008   F  15-24   10.0
46   AE  2008   F  25-34    4.0
47   AE  2008   F  35-44    1.0
48   AE  2008   F  45-54    1.0
49   AE  2008   F  55-64    3.0
50   AE  2008   F    >65    3.0